version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-image
    container_name: backend-cont
    ports:
      - "5000:5000"
    networks:
      - tiller-network
    env_file:
      - ./.env
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    command: ["flask", "run"]
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - tiller-network

  db:

  nginx:

volumes:

networks:
  tiller-network