name: Greetings
run-name: Greeting CI
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          issue-message: "👋 Hello @${{github.actor}}, thank you for opening an issue!. Your feedback is invaluable to us."
          pr-message: "🎉 Thank you @${{github.actor}} for your first pull request!.We appreciate your contribution to the project"
